plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.videokit'
version = '0.1.1'

android {
  namespace "expo.modules.videokit"
  defaultConfig {
    versionCode 2
    versionName "0.1.1"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("com.github.xentechltd:android-video-kit:v1.0.1")
}
